//Añade a marcadores
javascript:(function(){var analysisResults=[];function analyzeHeadings(){var h1Elements=document.evaluate("//h1",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);var h2Elements=document.evaluate("//h2",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);analysisResults.push(`<tr><th colspan="2">Encabezados</th></tr>`);if(h1Elements.snapshotLength>0){for(var i=0;i<h1Elements.snapshotLength;i++){var h1=h1Elements.snapshotItem(i).textContent.trim();analysisResults.push(`<tr><td>H1</td><td>${h1}</td></tr>`)}}
if(h2Elements.snapshotLength>0){for(var i=0;i<h2Elements.snapshotLength;i++){var h2=h2Elements.snapshotItem(i).textContent.trim();analysisResults.push(`<tr><td>H2</td><td>${h2}</td></tr>`)}}}
function analyzeLinks(){var internalLinks=document.evaluate("//a[not(contains(@href, 'http')) or contains(@href, '"+location.hostname+"')]",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);var externalLinks=document.evaluate("//a[contains(@href, 'http') and not(contains(@href, '"+location.hostname+"'))]",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);analysisResults.push(`<tr><th colspan="2">Enlaces</th></tr>`);analysisResults.push(`<tr><td>Enlaces internos</td><td>${internalLinks.snapshotLength}</td></tr>`);analysisResults.push(`<tr><td>Enlaces externos</td><td>${externalLinks.snapshotLength}</td></tr>`);if(internalLinks.snapshotLength>0){for(var i=0;i<internalLinks.snapshotLength;i++){var link=internalLinks.snapshotItem(i);analysisResults.push(`<tr><td>Interno</td><td><a href="${link.href}" target="_blank">${link.textContent.trim() || link.href}</a></td></tr>`)}}
if(externalLinks.snapshotLength>0){for(var i=0;i<externalLinks.snapshotLength;i++){var link=externalLinks.snapshotItem(i);analysisResults.push(`<tr><td>Externo</td><td><a href="${link.href}" target="_blank">${link.textContent.trim() || link.href}</a></td></tr>`)}}
var paramRegex=/\?.+=.+/;var paramLinksCount=0;for(var i=0;i<internalLinks.snapshotLength;i++){var link=internalLinks.snapshotItem(i);if(paramRegex.test(link.href)){paramLinksCount++}}
analysisResults.push(`<tr><td>Enlaces internos con parámetros</td><td>${paramLinksCount}</td></tr>`)}
function analyzeJSONLD(){var jsonldScripts=document.evaluate("//script[@type='application/ld+json']",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);if(jsonldScripts.snapshotLength>0){analysisResults.push(`<tr><th colspan="2">JSON-LD</th></tr>`);analysisResults.push(`<tr><td>Scripts JSON-LD encontrados</td><td>${jsonldScripts.snapshotLength}</td></tr>`);for(var i=0;i<jsonldScripts.snapshotLength;i++){var scriptContent=jsonldScripts.snapshotItem(i).textContent;var typeRegex=/"@type":\s*"([^"]+)"/g;var match;var types=[];while((match=typeRegex.exec(scriptContent))!==null){types.push(match[1])}
analysisResults.push(`<tr><td>Tipos de datos estructurados</td><td>${types.join(', ')}</td></tr>`)}}else{analysisResults.push(`<tr><td colspan="2">No se encontraron scripts JSON-LD.</td></tr>`)}}
function analyzeMetaRobots(){var robotsMeta=document.evaluate("//meta[@name='robots']",document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;if(robotsMeta){analysisResults.push(`<tr><th colspan="2">Meta Robots</th></tr>`);analysisResults.push(`<tr><td>Meta Robots</td><td>${robotsMeta.content}</td></tr>`)}else{analysisResults.push(`<tr><td colspan="2">No se encontró etiqueta Meta Robots.</td></tr>`)}}
function analyzeHreflangs(){var hreflangs=document.evaluate("//link[@rel='alternate'][@hreflang]",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);if(hreflangs.snapshotLength>0){analysisResults.push(`<tr><th colspan="2">Hreflangs</th></tr>`);analysisResults.push(`<tr><td>Etiquetas hreflang encontradas</td><td>${hreflangs.snapshotLength}</td></tr>`);for(var i=0;i<hreflangs.snapshotLength;i++){var hreflang=hreflangs.snapshotItem(i);analysisResults.push(`<tr><td>${hreflang.getAttribute('hreflang')}</td><td>${hreflang.getAttribute('href')}</td></tr>`)}}else{analysisResults.push(`<tr><td colspan="2">No se encontraron etiquetas hreflang.</td></tr>`)}}
function analyzeKeywordDensity(){var text=document.body.innerText.toLowerCase().replace(/[\s,\.\(\)\[\]"'!?:;]+/g,' ').trim();var phrases=text.match(/\b\w+\b \b\w+\b \b\w+\b/g);var phraseCount={};phrases.forEach(function(phrase){if(!phraseCount[phrase]){phraseCount[phrase]=0}
phraseCount[phrase]++});var sortedPhrases=Object.keys(phraseCount).sort(function(a,b){return phraseCount[b]-phraseCount[a]});var topPhrase=sortedPhrases[0];analysisResults.push(`<tr><th colspan="2">Palabra Clave Potencial</th></tr>`);analysisResults.push(`<tr><td>Frase más repetida</td><td>${topPhrase} (${phraseCount[topPhrase]} veces)</td></tr>`)}
analyzeHeadings();analyzeLinks();analyzeJSONLD();analyzeMetaRobots();analyzeHreflangs();analyzeKeywordDensity();var modal=document.createElement('div');modal.style.position='fixed';modal.style.top='5%';modal.style.left='5%';modal.style.width='90%';modal.style.height='85%';modal.style.overflow='auto';modal.style.backgroundColor='white';modal.style.padding='20px';modal.style.boxShadow='0 0 10px rgba(0, 0, 0, 0.5)';modal.style.zIndex='10000';modal.style.fontFamily='Arial, sans-serif';var modalContent=`<h2>Análisis SEO Técnico</h2><table border="1" cellpadding="5" cellspacing="0" style="width:100%; border-collapse: collapse;">`;analysisResults.forEach(function(result){modalContent+=result});modalContent+=`</table>`;modalContent+=`<p style="margin-top: 20px; font-size: 12px; color: #555;">Desarrollado por <a href="https://linkedin.com/in/aliciaruiz20/" target="_blank" style="color: #0073b1;">Alicia Ruiz</a> con la inestimable ayuda de ChatGPT</p>`;var closeButton=document.createElement('button');closeButton.innerText='Cerrar';closeButton.style.marginTop='20px';closeButton.style.padding='10px 20px';closeButton.style.backgroundColor='#0073b1';closeButton.style.color='white';closeButton.style.border='none';closeButton.style.cursor='pointer';closeButton.onclick=function(){document.body.removeChild(modal)};modal.innerHTML=modalContent;modal.appendChild(closeButton);document.body.appendChild(modal)})()
